# Generated by Django 5.0.3 on 2024-12-25 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_created_at_userotp_timestamp_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userotp",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="userotp",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
